---
abstract: 'Perl Module Tools'
author:
  - 'Mark Leighton Fisher <markleightonfisher@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: pmtools
requires:
  perl: 5.008008
version: 2.0.0
x_contributors:
  - 'Mark Leighton Fisher <fisherscreek.consulting@gmail.com>'
  - 'Mark Leighton Fisher <markleightonfisher@snoopy.local>'
